# Numpy(numerical python):
  * NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
  * Numpy is also incredibly fast, as it has bindings to C libraries. 
  * For more info on why you would want to use Arrays instead of lists, check out this great StackOverflow post.


# Using numpy
  * once youve installed numpy u can import it as a library.

In [99]:
!pip install numpy

In [100]:
import numpy as np  #import the package

In [101]:
#fist pass the data inthe list
lst = [1,2,3,4,5]
lst 

[1, 2, 3, 4, 5]

In [102]:
#convert to the numpy array 
np.array(lst)

array([1, 2, 3, 4, 5])

In [103]:
#data into the matrix
matrix = [
          [1,2,3],
          [4,5,6],
          [7,8,9]
]

In [104]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods
  * There are lots of built-in ways to generate Arrays
  * arange:
      * Return evenly spaced values within a given interval.

In [105]:
#create a range function like example for loop range
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
# arange() using stepinterval
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [107]:
#generate zeros in array
np.zeros(3)

array([0., 0., 0.])

In [108]:
#generate zeros in matrix 
np.zeros((5,5)) #fun ku

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [109]:
#generate ones in the array 
np.ones(3)

array([1., 1., 1.])

In [110]:
#generate onces in matrix
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace:
  * Return evenly spaced numbers over a specified interval.

In [111]:
# generate linspace  separate the value in particular range value
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [112]:
#genrate line space large anount of data
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# eye() 
  * creates an identity matrix.


In [113]:
# generate a identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
# generate a identity matrix in matrix form
np.eye(5,5)   #like 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random
  * Numpy also has lots of ways to create random number arrays:
  # rand () 
    * it only cover uniform ditribution the value might be uniform in 0.
    * create an array of the given shape and populate it with random samples from a uniform distribution over[0,1].

In [115]:
# generate random number in array.
np.random.rand(2)

array([0.1468793, 0.3388806])

In [116]:
# generate random number in matrix format.
np.random.rand(3,3)

array([[0.38109611, 0.92138997, 0.21798846],
       [0.99626535, 0.16860372, 0.87601416],
       [0.79393021, 0.38160169, 0.83228938]])

# randn
  * it cover only normal ditribution from value might be 0 and 1.
  * Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:


In [117]:
# like wise same for randn in rand like
np.random.randn(2)   #use this fun randn()

array([ 0.12099078, -0.18245663])

In [118]:
# generate a matrix form.
np.random.randn(5,5)

array([[ 0.11443886, -1.04222301,  0.69532503, -0.5165728 , -0.11248981],
       [ 0.2066307 ,  0.53328035, -1.44173545,  0.31632138,  0.27485668],
       [ 1.27477325,  1.69021442,  2.34010912,  1.96573797, -1.37394449],
       [ 0.3695191 ,  0.47095702, -1.81789607,  0.85270608,  0.93253386],
       [ 0.54865504, -1.24157802,  0.13632516, -0.98265397,  0.59598697]])

# randint
  * is random integer value is given.
  * return random integer from low (inclusive) to high (exclusive).

In [119]:
# gennerate a random value in particular range val
np.random.randint(1,6) #this used some games

2

In [120]:
np.random.randint(1,100)

27

In [121]:
# generate a random 10 value in particular range
np.random.randint(1,5,10) #this the value inthe step interval

array([1, 3, 3, 1, 3, 1, 3, 4, 1, 3])

In [122]:
np.random.randint(1,100,10)

array([79, 66, 75, 22,  2, 95, 72, 18, 44, 93])

# Array Attributes and Methods
  * Let's discuss some useful attributes and methods or an array.

In [123]:
arr = np.arange(25)
ranarr = np.random.randint(1,50,10)

In [124]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [125]:
ranarr

array([10, 15, 37, 47,  1, 47, 11, 44, 38, 35])

# Reshape
  * In Pandas data reshaping means the transformation of the structure of a table or vector (i.e. DataFrame or Series) to make it suitable for further analysis
  * returns an array containing the same data with a new shape.

In [126]:
arr.shape # how many value inthe array like count

(25,)

In [127]:
ranarr.shape

(10,)

In [128]:
# generate the value reshape inthe arr 
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max,min,argmax,argmin
  * These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [129]:
ranarr

array([10, 15, 37, 47,  1, 47, 11, 44, 38, 35])

In [130]:
# find max in the ranarr
ranarr.max()

47

In [131]:
# find min in the ranarr
ranarr.min()

1

In [132]:
# find argmin in the ranarr
ranarr.argmax() # wch position the max value is here index value positionhi

3

In [133]:
# find argmin()
ranarr.argmin()

4

# Shape
  * Shape is an attribute that arrays have (not a method):




In [134]:
#vector 
arr.shape

(25,)

In [135]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [136]:
# reshpe check in the shape
arr.reshape(1,25).shape

(1, 25)

In [137]:
# to vale change in th arr
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [138]:
# check the shape in the reshape
arr.reshape(25,1).shape

(25, 1)

# dtype
  * You can also grab the data type of the object in the array.

In [139]:
arr.dtype

dtype('int64')

In [140]:
# like the value inthe what type of data type 
a = [2.3,4.5]
a = np.array(a)

In [141]:
a.dtype

dtype('float64')

# Numpy indexing and selection
  * in this lecture we will discuss how tho select elements or groups of elements from an array.

In [142]:
import numpy as np

In [143]:
# creating sample array
arr = np.arange(0,11)

In [144]:
#display the arr value
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket Indexing and Selection
  * The simplest way to pick one or some elements of an array looks very similar to python lists:

In [145]:
# slicing the value inthe get value at an index 
arr[2]  # using normal form

2

In [146]:
# normal value inthe python slicing 
# get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [147]:
# get value in a range 
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting
  * Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [148]:
# setting a value with index range (broadcasting)
arr[0:5] = 100 #the assign value inthe 100
arr # show array vanthu fulla maritum maripuditum 
#reset pannnum numpyt main mistake.

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [149]:
arr[:]=100  # full value inthe point 
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [150]:
# reset array,well see ehy i had to reset in a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
# diff slice doing 
s = arr[0:5].copy() #arr  slice copy is stored in s 

In [152]:
s

array([0, 1, 2, 3, 4])

In [153]:
s[:]= 99  # arr copy irrukku s la s = arr copy
s

array([99, 99, 99, 99, 99])

In [154]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)
  * how 2d array index pandrathu.
  * The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [155]:
# create matrix
mat2 = np.array([
   [1,2,3], # 0 th row 
   [4,5,6], # 1 th row
   [7,8,9]   # 2 th row           
])

In [156]:
mat2.shape #view shape

(3, 3)

In [157]:
# 2d matrix slice panna porom 
mat2[0]  # view first row 

array([1, 2, 3])

In [158]:
# slicing one coumn and one row in particular
mat2[1][1] # like wise first row first column

5

In [159]:
# simple another way
mat2[1,1]  # same value

5

In [160]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
# now slice inthe matrix format
mat2[1:,1:] # first row start and end then
# firs coumn and end of all coulum .


array([[5, 6],
       [8, 9]])

In [162]:
mat2[1:,:] #first row and all column

array([[4, 5, 6],
       [7, 8, 9]])

In [163]:
mat2[1][0]

4

In [164]:
mat2[:2,1:]

array([[2, 3],
       [5, 6]])

In [165]:
mat2[:,2]

array([3, 6, 9])

In [166]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [167]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [168]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [169]:
# Getting individual element value
arr_2d[1,0]

20

In [170]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [171]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [172]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# fancy indexing
  * fancy indexing like wise beauty of indexing.
  * Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [173]:
#Set up matrix
arr2d = np.zeros((10,10))

In [174]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [175]:
#Length of array
arr_length = arr2d.shape[1] # like 1 means is the row

In [176]:
arr_length

10

In [177]:
# set up array
for i in range(arr_length):
  arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [178]:
# some order inthe array
arr2d[[2,3,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [179]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Selection
   * selection means namakku thevaiyana datava  select pandrathu.
   * Let's briefly go over how to use brackets for selection based off of comparison operators.

In [180]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
# conditio fix pandrom show pandrathu boolean varum
ar > 4 # condithion wrong na false varum

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [182]:
boo_arr = ar>4

In [183]:
boo_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [184]:
# normal list illan any clean view use array
ar[ar>4] # condition form pannitu ennaoperotor[]

array([ 5,  6,  7,  8,  9, 10])

In [185]:
# ippo equ example will show 
ar[ar==2]

array([2])

# Numby operations
  # Arithmatic
   * You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [186]:
# create a data inthe 10 numbers 
a = np.arange(0,11)

In [187]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [188]:
# why use numpy so easy and low code did u add a list 
# python program is some like complicated code.
a + a  # add a two list(array)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [189]:
# mulitiply a two no array
a*a  # multiple a two array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [190]:
# sub a two list (array)
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [191]:
# Warning on division by zero, but not an error!
# Just replaced with nan
a/a  # nan means not a number

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [192]:
1/a  # like division inthe normal form. 0/1 is infiniy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [193]:
# like usea/1 not same value
a/1  # like  a created value like same value

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [194]:
# use cube like a**3
a**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

# Universal Array Functions
  * like universal array fun means like min,max wise sequre root ,exp finded.
  * Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [196]:
# this the method for find sqrt root
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [197]:
# the exponential value find
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [198]:
# find max 
np.max(a)

10

In [199]:
# min
np.min(a)

0

In [200]:
# find log
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [201]:
# find sin
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [202]:
# find cos
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])